/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerDisplay;
import Controller.ControllerGroup;
import Controller.ControllerModify;
import Controller.ControllerRemove;
import Controller.ControllerUnGroup;
import Controller.Controller_Add;
import Model.Shape;
import Model.ShapeFactory;
import Model.ShapeManager;
import Model.Tool;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JColorChooser;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 * Cette classe représente un ensemble de gestionnaires d'événements et de
 * méthodes pour contrôler l'interface utilisateur
 * et les interactions avec le gestionnaire de formes géométriques
 * (`ShapeManager`) ainsi que l'affichage graphique.
 * Elle gère la sélection d'outils, la modification de formes, le regroupement,
 * le dégroupement, la suppression de formes,
 * la gestion des couleurs, et d'autres interactions avec les composants
 * graphiques.
 * 
 * Elle implémente également l'interface `Observer` pour réagir aux mises à jour
 * du modèle et mettre à jour l'affichage.
 * 
 * @author adrien.peytavie
 */
public class Window extends javax.swing.JFrame implements Observer {

        /**
         * Le composant graphique utilisé pour le dessin des formes géométriques.
         */
        private final GraphicsPainter painter;

        /**
         * Le gestionnaire des formes géométriques qui gère toutes les opérations liées
         * aux formes.
         */
        private ShapeManager data;

        /**
         * La fabrique de formes utilisée pour créer de nouvelles formes géométriques.
         */
        private ShapeFactory s;

        /**
         * L'outil actuellement sélectionné pour le dessin (ex. : Cercle, Carré, etc.).
         */
        private Tool tool;

        /**
         * Le contrôleur de modification utilisé pour effectuer des modifications sur
         * les formes géométriques.
         */
        private ControllerModify caModify;

        /**
         * Un indicateur booléen pour vérifier si une modification est en cours.
         */
        private Boolean isModify = false;

        /**
         * La forme géométrique en cours de modification.
         */
        private Shape shapeModify;

        /**
         * La nouvelle couleur sélectionnée pour la forme géométrique en cours de
         * création ou de modification.
         */
        private Color newColor;

        /**
         * Creates new form Window
         * 
         * @param _data
         */
        public Window(ShapeManager _data, ShapeFactory _s) {
                initComponents();
                this.tool = null;
                data = _data;
                s = _s;
                data.addObserver(this);
                caModify = new ControllerModify(data);
                painter = new GraphicsPainter(data);
                jSpinnerHeight.setVisible(false);
                jLabelHeight.setVisible(false);
                jPanel1.setLayout(new java.awt.GridLayout(1, 1));
                jPanel1.add(painter);

                DefaultMutableTreeNode root = new DefaultMutableTreeNode("Empty");
                jTree_Objects.setModel(new DefaultTreeModel(root));
                pack();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jPanel4 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jButton_Remove = new javax.swing.JButton();
                jButton_Group = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTree_Objects = new javax.swing.JTree();
                jLabel1 = new javax.swing.JLabel();
                jButton_UnGroup = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jSpinnerPositionX = new javax.swing.JSpinner();
                jSpinnerPositionY = new javax.swing.JSpinner();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jSpinnerRadius = new javax.swing.JSpinner();
                jLabel6 = new javax.swing.JLabel();
                jButtonColor = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextPaneInformations = new javax.swing.JTextPane();
                jSpinnerHeight = new javax.swing.JSpinner();
                jLabelHeight = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jRadioCircle = new javax.swing.JRadioButton();
                jRadioSquare = new javax.swing.JRadioButton();
                jRadioRectangle = new javax.swing.JRadioButton();
                jButton_Add = new javax.swing.JButton();
                jRadioTree = new javax.swing.JRadioButton();
                jRadioCar = new javax.swing.JRadioButton();
                jRadioHouse = new javax.swing.JRadioButton();

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Graphics Editor");

                jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jPanel1MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 592, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 461, Short.MAX_VALUE));

                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jButton_Remove.setText("Remove");
                jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_RemoveActionPerformed(evt);
                        }
                });

                jButton_Group.setText("Group");
                jButton_Group.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_GroupActionPerformed(evt);
                        }
                });

                jTree_Objects.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTree_ObjectsMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(jTree_Objects);

                jLabel1.setText("Properties");

                jButton_UnGroup.setText("UnGroup");
                jButton_UnGroup.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_UnGroupActionPerformed(evt);
                        }
                });

                jLabel2.setText("Center");

                jSpinnerPositionX.setEnabled(false);
                jSpinnerPositionX.setMinimumSize(new java.awt.Dimension(80, 22));

                jSpinnerPositionY.setEnabled(false);

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel3.setText("x");

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel4.setText("y");

                jLabel5.setText("Radius");

                jSpinnerRadius.setEnabled(false);

                jLabel6.setText("Color");

                jButtonColor.setBackground(new java.awt.Color(255, 0, 0));
                jButtonColor.setText("   ");
                jButtonColor.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonColorActionPerformed(evt);
                        }
                });

                jTextPaneInformations.setEnabled(false);
                jScrollPane2.setViewportView(jTextPaneInformations);

                jSpinnerHeight.setEnabled(false);

                jLabelHeight.setText("height");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(27, 27, 27)
                                                                                                .addComponent(jLabel6))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel2)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                17,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel5)))
                                                                .addGap(6, 6, 6)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(22, 22, 22)
                                                                                                .addComponent(jButtonColor,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                80,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jSpinnerRadius,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                80,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jSpinnerPositionX,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                80,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                15,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabelHeight,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                37,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jSpinnerPositionY,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jSpinnerHeight,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 22, Short.MAX_VALUE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane1)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jButton_Remove)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton_Group)
                                                                                                .addGap(8, 8, 8)
                                                                                                .addComponent(jButton_UnGroup))
                                                                                .addComponent(jScrollPane2))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jSpinnerPositionX,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jSpinnerPositionY,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel4))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jSpinnerRadius,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jSpinnerHeight,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelHeight))
                                                                .addGap(8, 8, 8)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jButtonColor))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton_Group)
                                                                                .addComponent(jButton_Remove)
                                                                                .addComponent(jButton_UnGroup))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0, Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
                jPanel3.setMaximumSize(new java.awt.Dimension(32767, 100));

                buttonGroup1.add(jRadioCircle);
                jRadioCircle.setText("Circle");
                jRadioCircle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioCircleActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioSquare);
                jRadioSquare.setText("Square");
                jRadioSquare.setToolTipText("");
                jRadioSquare.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioSquareActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioRectangle);
                jRadioRectangle.setText("Rectangle");
                jRadioRectangle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioRectangleActionPerformed(evt);
                        }
                });

                jButton_Add.setText("Add");
                jButton_Add.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_AddActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioTree);
                jRadioTree.setText("Tree");
                jRadioTree.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioTreeActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioCar);
                jRadioCar.setText("Car");
                jRadioCar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioCarActionPerformed(evt);
                        }
                });

                buttonGroup1.add(jRadioHouse);
                jRadioHouse.setText("House");
                jRadioHouse.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioHouseActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jRadioCircle,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                65,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioSquare,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                71,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioRectangle)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioTree)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioCar)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jRadioHouse)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton_Add)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jRadioCircle)
                                                                                .addComponent(jRadioSquare)
                                                                                .addComponent(jRadioRectangle)
                                                                                .addComponent(jButton_Add)
                                                                                .addComponent(jRadioTree)
                                                                                .addComponent(jRadioCar)
                                                                                .addComponent(jRadioHouse))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Cette méthode est appelée lorsque le bouton radio "Cercle" est activé.
         * Elle sélectionne l'outil "Cercle" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioCircleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioCircleActionPerformed
                tool = Tool.CIRCLE;
        }// GEN-LAST:event_jRadioCircleActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton radio "Voiture" est activé.
         * Elle sélectionne l'outil "Voiture" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioCarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioCarActionPerformed
                tool = Tool.CAR;
        }// GEN-LAST:event_jRadioCarActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton radio "Carré" est activé.
         * Elle sélectionne l'outil "Carré" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioSquareActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioSquareActionPerformed
                tool = Tool.SQUARE;
        }// GEN-LAST:event_jRadioSquareActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton radio "Rectangle" est activé.
         * Elle sélectionne l'outil "Rectangle" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioRectangleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioRectangleActionPerformed
                tool = Tool.RECTANGLE;
        }// GEN-LAST:event_jRadioRectangleActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton radio "Maison" est activé.
         * Elle sélectionne l'outil "Maison" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioHouseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioHouseActionPerformed
                tool = Tool.HOUSE;
        }// GEN-LAST:event_jRadioHouseActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton radio "Arbre" est activé.
         * Elle sélectionne l'outil "Arbre" pour le dessin.
         * 
         * @param evt L'événement d'action associé au bouton radio.
         */
        private void jRadioTreeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioTreeActionPerformed
                tool = Tool.TREE;
        }// GEN-LAST:event_jRadioTreeActionPerformed

        /**
         * Cette méthode est appelée lorsqu'un clic double est effectué sur l'arbre
         * visuel (`JTree`) représentant les formes géométriques.
         * Elle permet d'afficher les détails et les propriétés de la forme sélectionnée
         * pour une éventuelle modification.
         * 
         * @param evt L'événement de souris associé au clic double.
         */
        private void jTree_ObjectsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTree_ObjectsMouseClicked
                if (evt.getClickCount() == 2) {
                        ControllerDisplay caDisplay = new ControllerDisplay(data);
                        Shape shape = caDisplay.control(jTree_Objects.getSelectionPath(), jTextPaneInformations);
                        shapeModify = shape;
                        modifyShape(shapeModify);
                        enabledModify(shapeModify.getType());
                        isModify = true;
                }
        }// GEN-LAST:event_jTree_ObjectsMouseClicked

        /**
         * Cette méthode active ou désactive les éléments d'interface utilisateur pour
         * la modification d'une forme en fonction de son type.
         * 
         * @param type Le type de la forme géométrique (ex. : "Carré", "Rectangle",
         *             "Cercle", etc.).
         */
        private void enabledModify(String type) {
                this.jSpinnerPositionX.setEnabled(true);
                this.jSpinnerPositionY.setEnabled(true);
                this.jSpinnerRadius.setEnabled(true);
                this.jSpinnerRadius.setVisible(true);
                jLabel5.setVisible(true);
                jButton_Add.setText("Modify");
                if (type.equals("Square")) {
                        jLabel5.setText("size");
                } else if (type.equals("Rectangle")) {
                        jSpinnerHeight.setVisible(true);
                        jLabelHeight.setVisible(true);
                        jSpinnerHeight.setEnabled(true);
                        jLabel5.setText("width");
                } else if (type.equals("Tree") || type.equals("Car") || type.equals("House")) {
                        this.jSpinnerRadius.setVisible(false);
                        this.jSpinnerRadius.setEnabled(false);
                        jLabel5.setVisible(false);
                }
        }

        private void disableModify() {
                this.jSpinnerPositionX.setEnabled(false);
                this.jSpinnerPositionY.setEnabled(false);
                this.jSpinnerRadius.setEnabled(false);
                jLabel5.setText("radius");
                jSpinnerHeight.setVisible(false);
                jSpinnerHeight.setEnabled(false);
                jLabelHeight.setVisible(false);
                jButton_Add.setText("Add");
                jButtonColor.setBackground(Color.red);
        }

        /**
         * Cette méthode désactive les éléments d'interface utilisateur utilisés pour la
         * modification de forme.
         */
        private void modifyShape(Shape shape) {
                jSpinnerPositionX.setValue(shape.getX());
                jSpinnerPositionY.setValue(shape.getY());
                jButtonColor.setBackground(shape.getColor());
                if (shape.getType().equals("Circle")) {
                        jSpinnerRadius.setValue(shape.getRadius());
                        jLabel5.setText("radius");
                        jLabelHeight.setVisible(false);
                        jSpinnerHeight.setVisible(false);
                } else if (shape.getType().equals("Square")) {
                        jLabel5.setText("size");
                        jLabelHeight.setVisible(false);
                        jSpinnerHeight.setVisible(false);
                        jSpinnerHeight.setValue(shape.getSize());
                        jSpinnerRadius.setValue(shape.getSize());
                } else if (shape.getType().equals("Rectangle")) {
                        jSpinnerHeight.setVisible(true);
                        jLabelHeight.setVisible(true);
                        jSpinnerHeight.setValue(shape.getHeight());
                        jSpinnerRadius.setValue(shape.getWidth());
                        jLabel5.setText("width");
                }
        }

        /**
         * Cette méthode est appelée lorsqu'un clic est effectué sur le panneau de
         * dessin (`jPanel1`).
         * Elle permet de sélectionner une forme géométrique pour une éventuelle
         * modification.
         * 
         * @param evt L'événement de souris associé au clic.
         */
        private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MouseClicked
                if (evt.getClickCount() == 2) {
                        shapeModify = caModify.searchWithMouse(evt);
                        if (shapeModify != null) {
                                modifyShape(shapeModify);
                                enabledModify(shapeModify.getType());
                                isModify = true;
                        }
                }
        }// GEN-LAST:event_jPanel1MouseClicked

        /**
         * Cette méthode est appelée lorsque le bouton "Supprimer" est cliqué.
         * Elle permet de supprimer les formes géométriques sélectionnées.
         * 
         * @param evt L'événement d'action associé au bouton "Supprimer".
         */
        private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_RemoveActionPerformed
                ControllerRemove caRemove = new ControllerRemove(data);
                TreePath[] selectedPaths = jTree_Objects.getSelectionPaths();
                caRemove.control(selectedPaths, painter, jTree_Objects, jTextPaneInformations);

        }// GEN-LAST:event_jButton_RemoveActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton "Regrouper" est cliqué.
         * Elle permet de regrouper les formes géométriques sélectionnées.
         * 
         * @param evt L'événement d'action associé au bouton "Regrouper".
         */
        private void jButton_GroupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_GroupActionPerformed
                ControllerGroup caGroup = new ControllerGroup(data);
                TreePath[] selectedPaths = jTree_Objects.getSelectionPaths();
                caGroup.control(selectedPaths, jTextPaneInformations);
        }// GEN-LAST:event_jButton_GroupActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton "Dégrouper" est cliqué.
         * Elle permet de dégrouper les formes géométriques sélectionnées.
         * 
         * @param evt L'événement d'action associé au bouton "Dégrouper".
         */
        private void jButton_UnGroupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_UnGroupActionPerformed
                ControllerUnGroup caUnGroup = new ControllerUnGroup(data);
                TreePath[] selectedPaths = jTree_Objects.getSelectionPaths();
                caUnGroup.control(selectedPaths, jTextPaneInformations);
        }// GEN-LAST:event_jButton_UnGroupActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton "Ajouter/Modifier" est cliqué.
         * Elle permet d'ajouter une nouvelle forme géométrique ou de modifier la forme
         * sélectionnée, en fonction de l'état actuel.
         * 
         * @param evt L'événement d'action associé au bouton "Ajouter/Modifier".
         */
        private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AddActionPerformed
                if (!isModify) {
                        if (tool != null) {
                                Controller_Add sad = new Controller_Add(data, s);
                                sad.control(jButtonColor.getBackground(), tool, jTextPaneInformations);
                        } else {
                                jTextPaneInformations.setText("Select a button");
                        }

                } else {
                        caModify.control((int) jSpinnerPositionX.getValue(), (int) jSpinnerPositionY.getValue(),
                                        (int) jSpinnerRadius.getValue(),
                                        (int) jSpinnerRadius.getValue(),
                                        (int) jSpinnerHeight.getValue(),
                                        (int) jSpinnerRadius.getValue(), jButtonColor.getBackground(), shapeModify);
                        update(null, null);

                        jTextPaneInformations.setText("Modify succeeded");
                        isModify = false;
                        disableModify();
                }
        }// GEN-LAST:event_jButton_AddActionPerformed

        /**
         * Cette méthode est appelée lorsque le bouton de sélection de couleur est
         * cliqué.
         * Elle permet de choisir une nouvelle couleur pour la forme géométrique en
         * cours de création ou de modification.
         * 
         * @param evt L'événement d'action associé au bouton de sélection de couleur.
         */
        private void jButtonColorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonColorActionPerformed
                newColor = JColorChooser.showDialog(null, "Choose a color", Color.RED);

                jButtonColor.setBackground(newColor);
                jTextPaneInformations.setText("Color Changed");

        }// GEN-LAST:event_jButtonColorActionPerformed

        /**
         * Cette méthode met à jour l'affichage en réorganisant et en redessinant les
         * formes géométriques.
         * Elle est appelée en réponse aux mises à jour du modèle (`Observable`).
         * 
         * @param o   L'objet observable (non utilisé dans cette implémentation).
         * @param arg L'argument de mise à jour (non utilisé dans cette implémentation).
         */
        @Override
        public void update(Observable o, Object arg) {
                painter.revalidate();
                painter.repaint();

                // Reload JTree
                // TreePath[] selectionPaths = jTree_Objects.getSelectionPaths(); // need to
                // reload and not to use setModel...
                jTree_Objects.setModel(data.getTreeModel());
                expandAllNodes(jTree_Objects);
                // jTree_Objects.setSelectionPaths(selectionPaths);

                // Properties
                jSpinnerPositionX.setEnabled(false);
                jSpinnerPositionY.setEnabled(false);
                jSpinnerRadius.setEnabled(false);

        }

        /**
         * Cette méthode permet d'élargir tous les nœuds de l'arbre visuel (`JTree`)
         * pour les afficher en mode déplié.
         * 
         * @param tree L'arbre visuel (`JTree`) à déplier.
         */
        private void expandAllNodes(JTree tree) {
                int j = tree.getRowCount();
                int i = 0;
                while (i < j) {
                        tree.expandRow(i);
                        i += 1;
                        j = tree.getRowCount();
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButtonColor;
        private javax.swing.JButton jButton_Add;
        private javax.swing.JButton jButton_Group;
        private javax.swing.JButton jButton_Remove;
        private javax.swing.JButton jButton_UnGroup;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabelHeight;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JRadioButton jRadioCar;
        private javax.swing.JRadioButton jRadioCircle;
        private javax.swing.JRadioButton jRadioHouse;
        private javax.swing.JRadioButton jRadioRectangle;
        private javax.swing.JRadioButton jRadioSquare;
        private javax.swing.JRadioButton jRadioTree;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSpinner jSpinnerHeight;
        private javax.swing.JSpinner jSpinnerPositionX;
        private javax.swing.JSpinner jSpinnerPositionY;
        private javax.swing.JSpinner jSpinnerRadius;
        private javax.swing.JTextPane jTextPaneInformations;
        private javax.swing.JTree jTree_Objects;
        // End of variables declaration//GEN-END:variables

}
